version: '3.8'

services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: mybank-db-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secure_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mybank_prod}
      MYSQL_USER: ${MYSQL_USER:-mybank_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secure_user_password}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./api/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - mybank-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Symfony
  backend:
    image: mybank/backend:latest
    container_name: mybank-backend-prod
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET:-your-super-secret-key-change-this}
      DATABASE_URL: mysql://${MYSQL_USER:-mybank_user}:${MYSQL_PASSWORD:-secure_user_password}@database:3306/${MYSQL_DATABASE:-mybank_prod}?serverVersion=8.0&charset=utf8mb4
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:-https://yourdomain.com}
    ports:
      - "${BACKEND_PORT:-8082}:80"
    volumes:
      - backend_logs:/var/log/apache2
    networks:
      - mybank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/categories"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js
  frontend:
    image: mybank/frontend:latest
    container_name: mybank-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8082/api}
      NODE_ENV: production
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - mybank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Reverse Proxy Nginx (optionnel)
  nginx:
    image: nginx:alpine
    container_name: mybank-nginx-prod
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - mybank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data_prod:
    driver: local
  backend_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  mybank-network:
    driver: bridge
